---
# manifests/n8n/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  namespace: n8n
  labels:
    app: n8n
    component: worker
spec:
  replicas: 2  # You can adjust the number of workers
  selector:
    matchLabels:
      app: n8n
      component: worker
  template:
    metadata:
      labels:
        app: n8n
        component: worker
    spec:
      containers:
      - name: n8n-worker
        image: n8nio/n8n:latest
        imagePullPolicy: Always
        command: ["node", "/usr/local/lib/node_modules/n8n/bin/n8n", "worker"]
        envFrom:
        - configMapRef:
            name: n8n-config
        - secretRef:
            name: n8n-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-storage-pvc
