---
# Service to expose PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres-svc
spec:
  selector:
    app: n8n-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
